language: node_js

node_js:
  - "lts/*"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9
env:
  - CXX=g++-4.9

sudo: false

stages:
  - Test
  - name: Release
    if: branch = master AND commit_message !~ /(release|no-release)/

jobs:
  include:
    - stage: Release
      node_js: lts/*
      install: npm install --no-package-lock
      before_deploy:
        - git config user.email ${GITHUB_EMAIL:-"travis@travis-ci.org"}
        - git config user.name ${GITHUB_USER:-"Travis CI"}
        - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git checkout master
      deploy:
        skip_cleanup: true
        provider: script
        script: npm run release
        on:
          branch: master
